# Generated by Django 3.1.6 on 2021-03-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Время редактирования'),
        ),
    ]
