# Generated by Django 3.1.6 on 2021-03-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0002_auto_20210306_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Время редактирования'),
        ),
    ]
